[workspace]
authors = ["Riccardo Cappuzzo <riccardo.cappuzzo@gmail.com>"]
channels = ["conda-forge"]
name = "talk-30-min"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[tasks.render-slides]
cmd = "quarto render"

[dependencies]
quarto = ">=1.8.25,<2"
skrub = ">=0.6.2,<0.7"
polars = ">=1.35.1,<2"
papermill = ">=2.6.0,<3"
pandas = ">=2.3.3,<3"
pyarrow = ">=22.0.0,<23"
ipykernel = ">=7.1.0,<8"
pip = ">=25.2,<26"
